### PR TITLE
Use up/down button to switch between previous/next input

### PR DESCRIPTION
**Pull request by kevin996231**
As title.
Usage will be same as normal command line.

### CODE REVIEW

**Comment by tran-quang-thanh** [comment]
You should not put equal when compare 2 double numbers because it isnt't stored the same way as integers. For example, 0.1 + 0.2 == 0.3 will return false.

**Comment by kevin996231** [comment]
Did you mean the difference to word part?

**Comment by tran-quang-thanh** [comment]
What I mean is that you should put it as < not <= because <= won't work for case =

**Comment by kevin996231** [comment]
but 3*1.0/6 == 0.5 is true.
and that is all I need for demo.
I feel like 0.5 is safe since 0.5=1/2

I can change it to <0.51 or < 0.6 if you wish

**Comment by kevin996231** [comment]
or just compare it in integer
like difference * 2 <= word.length

**Comment by kevin996231** [comment]
Create excel file during testing and delete them after tests are done
Fix edit and search bugs

**Pull request merged**
