### PR TITLE
Add FrequentlySearched feature

### PR DESCRIPTION
**Pull request by tessa-z**
Users can see words they have searched for most frequently

### CODE REVIEW

**Comment by tran-quang-thanh** [comment]
I think that there is no need to create a tree map for frequently search. If you need it to quiz uses, you can use a map between an integer representing the number of search with a list of words that are searched for that amount of times

**Comment by tessa-z** [comment]
> I think that there is no need to create a tree map for frequently search. If you need it to quiz uses, you can use a map between an integer representing the number of search with a list of words that are searched for that amount of times

Yup true! I was thinking of using an ordered map with the integer as keys and the word as values as well, but it seems that there aren't native data structures that can allow me to hold duplicate keys.

Looks like I can use [MultiValuedMap (Section 4.2)](https://www.baeldung.com/java-map-duplicate-keys) but it's implemented with an Arraylist to each key which would be quite inefficient when I want to update the search count for a word (especially when updating from 0 to 1, since the arraylist mapped to 0 would be the longest). Did I miss out on a better solution/If anyone has any other implementation? Otherwise I'll just use this first since I doubt run speed is very high priority for this application.

@AY1920S1-CS2113-T14-3

**Comment by tran-quang-thanh** [comment]
I think you can use a map with an integer as key to map with hashmap or treemap of words, then I can update it so it can be used, or may be an arraylist of hashmap/hashtree, and the integer is the index

**Comment by tessa-z** [comment]
@tran-quang-thanh I've added a new commit where I added another wordCount that is initialised on the creation of the wordBank. This wordCount maps the searchCount (key) to a TreeMap containing words searched for searchCount number of times. I've also implemented the code where the searchCount is updated every time a word is searched for by the user. Thanks for reviewing btw!

**Comment by tran-quang-thanh** [comment]
For your wordCount attribute of wordBank, you don't need to create it as a TreeMap<Integer,TreeMap>, instead just ArrayList<TreeMap>, because integer you set as key can be used as index of ArrayList

**Comment by tessa-z** [comment]
I did consider that following your first suggestion but that would mean some of the array space is just empty though. e.g. when my search count is only 0 and 3 then the space in between from 1-2 won't be used. Wouldn't that lead to space wastage?

**Review by tran-quang-thanh — APPROVED** [review]

**Pull request merged**
