### PR TITLE
Modularise WordCount 

### PR DESCRIPTION
**Pull request by tessa-z**
Separate wordcount into its own class following principle of SOC

### CODE REVIEW

**Comment by tran-quang-thanh** [comment]
What I think better is that you create a big Bank where you store the WordBank, WordCount, TagList, etc so whenever we need to add a new one we don't need to fix all the files. That big Bank will have attribute WordBank, WordCount, TagList, etc

**Comment by tessa-z** [comment]
Ooh okok

**Review by kevin996231 — COMMENTED** [review]
Currently if we delete word from wordbank, it will still be in wordcount right?
And due to the structure we can't easily delete the word in wordcount.
Maybe we can add a attribute "count" in class word so that when we delete the word, we can access "count" and delete the word from wordcount.

**Comment by tran-quang-thanh** [comment]
> Currently if we delete word from wordbank, it will still be in wordcount right?
> And due to the structure we can't easily delete the word in wordcount.
> Maybe we can add a attribute "count" in class word so that when we delete the word, we can access "count" and delete the word from wordcount.

Actually we already have it called numberOfSearch in Word object

**Comment by tessa-z** [comment]
^Yup I'll be adding in the deletion part

**Comment by tran-quang-thanh** [comment]
I think you are have misunderstood what I said. What I mean was that you create a Bank object which contains everything, and the user will only interact with Bank, and Bank will call methods from WordBank, WordCount, etc. For now you are still using different object WordCount, WordBank to interact with user

**Comment by tessa-z** [comment]
> What I think better is that you create a big Bank where you store the WordBank, WordCount, TagList, etc so whenever we need to add a new one we don't need to fix all the files. That big Bank will have attribute WordBank, WordCount, TagList, etc

I tried extracting the Bank class in commit f2d5c38! can help see if it's alright?

**Comment by tran-quang-thanh** [comment]
> > What I think better is that you create a big Bank where you store the WordBank, WordCount, TagList, etc so whenever we need to add a new one we don't need to fix all the files. That big Bank will have attribute WordBank, WordCount, TagList, etc
> 
> I tried extracting the Bank class in commit [f2d5c38](https://github.com/AY1920S1-CS2113-T14-3/main/commit/f2d5c381e1c7d10270cba2262547b7ff56ae2cb9)! can help see if it's alright?

I know you have a Bank class but I think for now it doesn't do anything. What I meant was that you just put one Bank class in execute methods, load, etc, and Bank class will call it from other objects

**Comment by tran-quang-thanh** [comment]
I have created a pull request as an example for my Bank class. It contains WordBank and TagBank

**Pull request merged**
